name: CI/CD

on:
  push:
    branches: [sub]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build docker-compose
        run: docker-compose -f docker-compose.yml up --build -d
        
  secret-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Secret scanning
        uses: max/secret-scan@master
        with:
          exclude_path: '/exclude.txt'
