---
name: CTFd Main CI

on:
  push:
    branches: [sub]

env:
  DEP_PATH: requirements.txt
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build docker-compose
        run: docker-compose -f docker-compose.yml up --build -d

  SecretScan:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2 
      - 
        name: Exclude paths
        run: |
          mkdir -p logs/
          echo 'CTFd/themes/' >> logs/exclude.txt
          echo 'CHANGELOG.md' >> logs/exclude.txt
          echo 'CTFd/utils/security/sanitize.py' >> logs/exclude.txt
          echo 'tests/users/test_auth.py' >> logs/exclude.txt
          echo 'tests/utils/test_email.py' >> logs/exclude.txt
          echo 'tests/api/v1/test_files.py' >> logs/exclude.txt
          echo 'tests/utils/test_encoding.py' >> logs/exclude.txt
          echo 'tests/utils/test_passwords.py' >> logs/exclude.txt
          echo 'yarn.lock' >> logs/exclude.txt
      -
        name: Find secrets
        uses: max/secret-scan@master
        with:
          exclude_path: 'logs/exclude.txt'

  PythonSafety:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master  
      - 
        name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - 
        name: Install Safety    
        run:
          pip install safety
      - 
        name: Create logs file
        run: mkdir -p logs/
      - 
        name: SCA Analysis
        run: safety check -r requirements.txt --full-report -i 40459 -i 42194 > logs/safety-logs.txt
      - 
        name: Upload logs  
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/safety-logs.txt

  Pyraider:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Pyraider
        run: |
          pip install pyraider
          pyraider check -f app/web/requirements.txt  
      -  
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/pyraider-logs.json

  