
name: CI

on:
  push:
    branches:
      - '2022-group2-CTFd'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build docker-compose
        run: docker-compose -f docker-compose.yml build

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2 
      - 
        name: Find secrets
        uses: max/secret-scan@master

  sca:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2   
      - 
        name: Create logs directory
        run: |
          mkdir -p logs/
      - 
        name: Python Safety
        run: |
          pip install safety
          safety check -r requirements.txt > logs/safety.txt
      - 
        name: Pyraider
        run: |
          pip install pyraider
          pyraider check -f requirements.txt > logs/pyraider.txt
      - 
        name: Upload python safety check results
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            logs/safety.txt
            logs/pyraider.txt